version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:17-jdk # Official OpenJDK 17 image
    environment:
      JAVA_HOME: /usr/local/openjdk-17 # Set the correct Java path
      ANDROID_HOME: /opt/android/sdk # Set Android SDK environment
      PATH: $PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools # Update PATH for Android tools
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install  # Install Node dependencies

      - run:
          name: Run Tests
          command: npm test -- --ci
          no_output_timeout: 20m # Increase timeout to 20 minutes

      - run:
          name: Build Android
          command: |
            cd android
            chmod +x gradlew # Ensure gradlew is executable
            ./gradlew assembleRelease # Build the Android app

workflows:
  version: 2
  build:
    jobs:
      - build
