version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install  # or yarn install if you're using Yarn
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Android
          command: |
            cd android
            ./gradlew assembleRelease  # Adjust for iOS if needed

workflows:
  version: 2
  build:
    jobs:
      - build
