version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17 # Use OpenJDK 17 Docker image
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk # Set to the correct Java path for the CircleCI OpenJDK image
      ANDROID_HOME: /opt/android/sdk # Set Android SDK environment
      PATH: $PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools # Update PATH for Android tools
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install  # Install Node dependencies

      - run:
          name: Run Tests
          command: npm test -- --ci
          no_output_timeout: 20m # Increase timeout to 20 minutes

      - run:
          name: Build Android
          command: |
            cd android
            chmod +x gradlew # Ensure gradlew is executable
            ./gradlew assembleRelease # Build the Android app

workflows:
  version: 2
  build:
    jobs:
      - build
