version: 2.1

jobs:
  build:
    docker:
      docker:
        - image: circleci/node:latest
    environment:
      JAVA_HOME: /usr/local/openjdk-11 # Set the correct Java path
      ANDROID_HOME: /opt/android/sdk # Set Android SDK environment
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install  # or yarn install if you're using Yarn

      - run:
          name: Run Tests
          command: npm test -- --ci
          no_output_timeout: 20m # Increase timeout to 20 minutes

      - run:
          name: Build Android
          command: |
            cd android
            ./gradlew assembleRelease # Adjust for iOS if need ed

workflows:
  version: 2
  build:
    jobs:
      - build
